# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb6ccd4f0693381f8491b31c74abe5b84c4eaac4f48cf78472812cadb0c16d869146d6fc2d0411492245097ee99c460f765ecfd4cb4b478ee4c1b19fd19c755

test:
  secret_key_base: b5feeb1914c6934517f0bdb757ad79ba2c984dabba6ecc0e17074bd8790e94aed051c94eafeb0ebca86cb5391cbab954d003acb48a32634cf2cf27719e970b8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
